<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <AssemblyName>syncfusion.spreadsheetdemo.wpf</AssemblyName>
    <RootNamespace>syncfusion.spreadsheetdemo.wpf</RootNamespace>
    <TargetFrameworkVersion></TargetFrameworkVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0-windows' ">
    <RuntimeHostConfigurationOption Include="Switch.System.Windows.Controls.DisableDynamicResourceOptimization" Value="true" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFRAMEWORK' ">
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xaml"></Reference>
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Compression.Base" Version="33.1.44" />
    <PackageReference Include="Syncfusion.ExcelChartToImageConverter.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.Licensing" Version="33.1.44" />
    <PackageReference Include="Syncfusion.SfCellGrid.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.SfChart.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.SfGridCommon.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.SfSpreadsheet.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.SfSpreadsheetHelper.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.Tools.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.SfSkinManager.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.Themes.Office2019White.WPF" Version="33.1.44" />
    <PackageReference Include="Syncfusion.XlsIO.Wpf" Version="33.1.44" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Data\SpreadsheetShowCase\Showcase.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\SfSpreadsheet.png" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="packages.config" />
    <None Remove="App.config" />
    <Compile Remove="App.xaml.cs" />
    <ApplicationDefinition Remove="App.xaml" />
  </ItemGroup>
  <Import Project="..\..\targets\MultiTargeting_Net80.targets" />
  <PropertyGroup Condition=" '$(TargetFramework)'=='net462' ">
    <SyncfusionAssemblyLocation>4.6.2</SyncfusionAssemblyLocation>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)'=='net8.0-windows' ">
    <SyncfusionAssemblyLocation>net8.0</SyncfusionAssemblyLocation>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)'=='net9.0-windows' ">
    <SyncfusionAssemblyLocation>net9.0</SyncfusionAssemblyLocation>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)'=='net462' ">
    <SyncfusionAssemblyLocation>4.6.2</SyncfusionAssemblyLocation>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)'=='net8.0-windows' ">
    <SyncfusionAssemblyLocation>net8.0</SyncfusionAssemblyLocation>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(TargetFramework)'=='net9.0-windows' ">
    <SyncfusionAssemblyLocation>net9.0</SyncfusionAssemblyLocation>
  </PropertyGroup>
</Project>